[common]
server_addr = "your_server_addr"
server_port = "7000"
token = "123456789"

[letsencryptvalidationport]
type = "http"
local_port = "80"
remote_port = "80"
subdomain = "subdomain"

[httpshomeassistant]
type = "https"
local_port = "8123"
remote_port = "443"
subdomain = "subdomain"
